### ISSUE TITLE
join-server unable to create local storage (NodeRed via Docker)

### ISSUE THREAD

**Issue by jasonalsing** [joaomgcd/node-red-contrib-join-joaoapps#10]
I have node-red installed via Docker and my data directory is configured to use host volume. eg:

```
node-red:
    container_name: node-red
    restart: always
    image: nodered/node-red-docker
    user: ${PUID}
    volumes:
      - ${USERDIR}/docker/node-red:/data
```
When I install the join module via the palette, the "Join Server" component creates a EEACCES: permission denied, mkdir('/usr/src/node-red') line 11

but all the node files are downloaded where there supposed to be in {USERDIR}/docker/node-red which is mounted via /data in the container. 

I see in join-server.js  line 11 it attempts to create the directory via the localStorage node(?) which is downloaded as part of the join package. 

var localStorage = new LocalStorage('./joinserver');

I think it's trying to create this in the wrong location. It should not be in /usr/src/node-red, it should be in the data directory of course. If I change the entry in join-server.js to:

var localStorage = new LocalStorage("/data/node_modules/node-red-contrib-join-joaoapps/joinserver");

And restart node-red all the components load and I can configure the Join Server in Node-Red.
